# Generated by Django 5.1.5 on 2025-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
